# coding: utf-8

"""
    Core API v2

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.data_casting_request import DataCastingRequest

class TestDataCastingRequest(unittest.TestCase):
    """DataCastingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataCastingRequest:
        """Test DataCastingRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataCastingRequest`
        """
        model = DataCastingRequest()
        if include_optional:
            return DataCastingRequest(
                url = '0',
                catalog_id = '0',
                workspace_id = '0',
                processor_id = '0',
                additional_links = [
                    null
                    ],
                subjects = [
                    openapi_client.models.subject.Subject(
                        id = '', 
                        name = '', )
                    ],
                collection = '',
                asset_filters = [
                    ''
                    ],
                path = '',
                casting = 'default',
                depth = 56,
                background_job_id = '',
                id = ''
            )
        else:
            return DataCastingRequest(
                url = '0',
                catalog_id = '0',
                workspace_id = '0',
                processor_id = '0',
        )
        """

    def testDataCastingRequest(self):
        """Test DataCastingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
