# coding: utf-8

"""
    TerrAPI

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.i_publication_request import IPublicationRequest

class TestIPublicationRequest(unittest.TestCase):
    """IPublicationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IPublicationRequest:
        """Test IPublicationRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IPublicationRequest`
        """
        model = IPublicationRequest()
        if include_optional:
            return IPublicationRequest(
                id = '',
                background_job_id = '',
                url = '',
                catalog_id = '',
                additional_links = [
                    {
                        'key' : null
                        }
                    ],
                subjects = [
                    openapi_client.models.i_subject.ISubject(
                        id = '', 
                        name = '', )
                    ],
                collection = '',
                depth = 56
            )
        else:
            return IPublicationRequest(
        )
        """

    def testIPublicationRequest(self):
        """Test IPublicationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
