# coding: utf-8

"""
    TerrAPI

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.publication_request import PublicationRequest

class TestPublicationRequest(unittest.TestCase):
    """PublicationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublicationRequest:
        """Test PublicationRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublicationRequest`
        """
        model = PublicationRequest()
        if include_optional:
            return PublicationRequest(
                id = '',
                catalog_id = '0',
                token = openapi_client.models.access_token.AccessToken(
                    id = '', 
                    principal_id = '0', 
                    token = '0', 
                    valid_to = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    refresh_token = '', 
                    id_token = '', ),
                url = '0',
                additional_links = [
                    {
                        'key' : null
                        }
                    ],
                subjects = [
                    openapi_client.models.subject.Subject(
                        id = '', 
                        name = '', )
                    ],
                collection = '',
                depth = 56,
                background_job_id = '',
                publication_link = [
                    {
                        'key' : null
                        }
                    ],
                context_id = '',
                properties = {
                    'key' : null
                    }
            )
        else:
            return PublicationRequest(
                catalog_id = '0',
                url = '0',
        )
        """

    def testPublicationRequest(self):
        """Test PublicationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
