# coding: utf-8

"""
    Core API v2

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.services_api import ServicesApi


class TestServicesApi(unittest.TestCase):
    """ServicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServicesApi()

    def tearDown(self) -> None:
        pass

    def test_cast_time_series(self) -> None:
        """Test case for cast_time_series

        Request casting for a time series.
        """
        pass

    def test_get_data_casting_status_async(self) -> None:
        """Test case for get_data_casting_status_async

        Get the status of a casting request
        """
        pass

    def test_post_data_casting(self) -> None:
        """Test case for post_data_casting

        Request casting for a generic data resource
        """
        pass


if __name__ == '__main__':
    unittest.main()
