# coding: utf-8

"""
    Core API v2

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.import_request_imported_link import ImportRequestImportedLink

class TestImportRequestImportedLink(unittest.TestCase):
    """ImportRequestImportedLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportRequestImportedLink:
        """Test ImportRequestImportedLink
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportRequestImportedLink`
        """
        model = ImportRequestImportedLink()
        if include_optional:
            return ImportRequestImportedLink(
                type = '',
                rel = '',
                title = '',
                href = ''
            )
        else:
            return ImportRequestImportedLink(
                rel = '',
        )
        """

    def testImportRequestImportedLink(self):
        """Test ImportRequestImportedLink"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
