# coding: utf-8

"""
    Core API v2

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.storage_api import StorageApi


class TestStorageApi(unittest.TestCase):
    """StorageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StorageApi()

    def tearDown(self) -> None:
        pass

    def test_claim_workspace(self) -> None:
        """Test case for claim_workspace

        Claim a workspace
        """
        pass

    def test_get_shared_folder_by_id(self) -> None:
        """Test case for get_shared_folder_by_id

        Get the shared folder information for a specific id
        """
        pass

    def test_get_workspace_by_id(self) -> None:
        """Test case for get_workspace_by_id

        Get the workspace information for a specific id
        """
        pass

    def test_get_workspace_import_status(self) -> None:
        """Test case for get_workspace_import_status

        Get Status of an import
        """
        pass

    def test_get_workspaces(self) -> None:
        """Test case for get_workspaces

        Get all the workspaces information related to an authenticated user
        """
        pass

    def test_share_folder(self) -> None:
        """Test case for share_folder

        Share a folder from a workspace with users
        """
        pass

    def test_v2_storage_download_post(self) -> None:
        """Test case for v2_storage_download_post

        Request a download URL for a given resource
        """
        pass

    def test_v2_storage_token_get(self) -> None:
        """Test case for v2_storage_token_get

        Get Credentials for specific storage point (e.g workspace, shared folder...)
        """
        pass

    def test_v2_storage_workspaces_workspace_id_import_catalog_post(self) -> None:
        """Test case for v2_storage_workspaces_workspace_id_import_catalog_post

        Import resources from exisiting catalog
        """
        pass


if __name__ == '__main__':
    unittest.main()
