# coding: utf-8

"""
    TerrAPI

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.resource_type import ResourceType

class TestResourceType(unittest.TestCase):
    """ResourceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceType(self):
        """Test ResourceType"""
        # inst = ResourceType()

if __name__ == '__main__':
    unittest.main()
