# coding: utf-8

"""
    TerrAPI

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.publication_status import PublicationStatus

class TestPublicationStatus(unittest.TestCase):
    """PublicationStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublicationStatus:
        """Test PublicationStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublicationStatus`
        """
        model = PublicationStatus()
        if include_optional:
            return PublicationStatus(
                request = openapi_client.models.i_publication_request.IPublicationRequest(
                    id = '', 
                    background_job_id = '', 
                    url = '', 
                    catalog_id = '', 
                    additional_links = [
                        {
                            'key' : null
                            }
                        ], 
                    subjects = [
                        openapi_client.models.i_subject.ISubject(
                            id = '', 
                            name = '', )
                        ], 
                    collection = '', 
                    depth = 56, ),
                identifier = '',
                status = 'Scheduled',
                links = [
                    {
                        'key' : null
                        }
                    ]
            )
        else:
            return PublicationStatus(
        )
        """

    def testPublicationStatus(self):
        """Test PublicationStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
