# coding: utf-8

"""
    Core API v2

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.data_casting_enum import DataCastingEnum

class TestDataCastingEnum(unittest.TestCase):
    """DataCastingEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataCastingEnum(self):
        """Test DataCastingEnum"""
        # inst = DataCastingEnum()

if __name__ == '__main__':
    unittest.main()
