# coding: utf-8

"""
    Core API v2

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.request_status import RequestStatus

class TestRequestStatus(unittest.TestCase):
    """RequestStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestStatus:
        """Test RequestStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestStatus`
        """
        model = RequestStatus()
        if include_optional:
            return RequestStatus(
                id = '',
                status = 'scheduled',
                links = [
                    null
                    ]
            )
        else:
            return RequestStatus(
        )
        """

    def testRequestStatus(self):
        """Test RequestStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
