# coding: utf-8

"""
    TerrAPI

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.inventory_type import InventoryType

class TestInventoryType(unittest.TestCase):
    """InventoryType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInventoryType(self):
        """Test InventoryType"""
        # inst = InventoryType()

if __name__ == '__main__':
    unittest.main()
