# coding: utf-8

"""
    Core API v2

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.resource_status_code import ResourceStatusCode

class TestResourceStatusCode(unittest.TestCase):
    """ResourceStatusCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceStatusCode(self):
        """Test ResourceStatusCode"""
        # inst = ResourceStatusCode()

if __name__ == '__main__':
    unittest.main()
