# coding: utf-8

"""
    TerrAPI

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.self_info import SelfInfo

class TestSelfInfo(unittest.TestCase):
    """SelfInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SelfInfo:
        """Test SelfInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SelfInfo`
        """
        model = SelfInfo()
        if include_optional:
            return SelfInfo(
                type = 'urn:resource:storage:workspace',
                name = '',
                var_self = ''
            )
        else:
            return SelfInfo(
        )
        """

    def testSelfInfo(self):
        """Test SelfInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
