# coding: utf-8

"""
    Core API v2

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.storage_type import StorageType

class TestStorageType(unittest.TestCase):
    """StorageType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageType(self):
        """Test StorageType"""
        # inst = StorageType()

if __name__ == '__main__':
    unittest.main()
