# coding: utf-8

"""
    TerrAPI

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.inventory_api import InventoryApi


class TestInventoryApi(unittest.TestCase):
    """InventoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InventoryApi()

    def tearDown(self) -> None:
        pass

    def test_claim_catalogue(self) -> None:
        """Test case for claim_catalogue

        Claim a catalogue
        """
        pass

    def test_get_catalogue_by_id(self) -> None:
        """Test case for get_catalogue_by_id

        Get the catalogue information for a specific id
        """
        pass

    def test_get_catalogue_publication_status(self) -> None:
        """Test case for get_catalogue_publication_status

        Get Status of an import
        """
        pass

    def test_get_catalogues(self) -> None:
        """Test case for get_catalogues

        Get all the catalogues information related to an authenticated user
        """
        pass

    def test_v2_inventory_catalogues_publish_post(self) -> None:
        """Test case for v2_inventory_catalogues_publish_post

        Submit a catalog publication request
        """
        pass

    def test_v2_inventory_token_get(self) -> None:
        """Test case for v2_inventory_token_get

        Get Credentials for specific inventory point (e.g catalog, collection)
        """
        pass


if __name__ == '__main__':
    unittest.main()
