# coding: utf-8

"""
    TerrAPI

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.catalog_publication_request import CatalogPublicationRequest

class TestCatalogPublicationRequest(unittest.TestCase):
    """CatalogPublicationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CatalogPublicationRequest:
        """Test CatalogPublicationRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CatalogPublicationRequest`
        """
        model = CatalogPublicationRequest()
        if include_optional:
            return CatalogPublicationRequest(
                url = '0',
                catalog_id = '',
                additional_links = [
                    {
                        'key' : null
                        }
                    ],
                subjects = [
                    openapi_client.models.subject.Subject(
                        id = '', 
                        name = '', )
                    ],
                collection = '',
                depth = 56
            )
        else:
            return CatalogPublicationRequest(
                url = '0',
        )
        """

    def testCatalogPublicationRequest(self):
        """Test CatalogPublicationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
