# coding: utf-8

"""
    TerrAPI

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.i_inventory_sts import IInventorySTS

class TestIInventorySTS(unittest.TestCase):
    """IInventorySTS unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IInventorySTS:
        """Test IInventorySTS
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IInventorySTS`
        """
        model = IInventorySTS()
        if include_optional:
            return IInventorySTS(
                api_key = '',
                token = '',
                expiration = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return IInventorySTS(
        )
        """

    def testIInventorySTS(self):
        """Test IInventorySTS"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
