# coding: utf-8

"""
    Core API v2

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.share_folder_request import ShareFolderRequest

class TestShareFolderRequest(unittest.TestCase):
    """ShareFolderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ShareFolderRequest:
        """Test ShareFolderRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ShareFolderRequest`
        """
        model = ShareFolderRequest()
        if include_optional:
            return ShareFolderRequest(
                path = '',
                users = [
                    ''
                    ]
            )
        else:
            return ShareFolderRequest(
        )
        """

    def testShareFolderRequest(self):
        """Test ShareFolderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
