# coding: utf-8

"""
    TerrAPI

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.import_status import ImportStatus

class TestImportStatus(unittest.TestCase):
    """ImportStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportStatus:
        """Test ImportStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportStatus`
        """
        model = ImportStatus()
        if include_optional:
            return ImportStatus(
                request = openapi_client.models.import_request.ImportRequest(
                    id = '', 
                    workspace_id = '0', 
                    url = '0', 
                    asset_filters = [
                        ''
                        ], 
                    path = '', 
                    fail_on_error = True, ),
                identifier = '',
                status = 'Scheduled',
                links = [
                    {
                        'key' : null
                        }
                    ]
            )
        else:
            return ImportStatus(
        )
        """

    def testImportStatus(self):
        """Test ImportStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
