# coding: utf-8

"""
    Core API v2

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.control_api import ControlApi


class TestControlApi(unittest.TestCase):
    """ControlApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ControlApi()

    def tearDown(self) -> None:
        pass

    def test_get_job_status(self) -> None:
        """Test case for get_job_status

        Get the status of a job
        """
        pass


if __name__ == '__main__':
    unittest.main()
