# coding: utf-8

"""
    TerrAPI

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.background_job_request_status import BackgroundJobRequestStatus

class TestBackgroundJobRequestStatus(unittest.TestCase):
    """BackgroundJobRequestStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BackgroundJobRequestStatus:
        """Test BackgroundJobRequestStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BackgroundJobRequestStatus`
        """
        model = BackgroundJobRequestStatus()
        if include_optional:
            return BackgroundJobRequestStatus(
                identifier = '',
                status = 'Scheduled',
                links = [
                    {
                        'key' : null
                        }
                    ]
            )
        else:
            return BackgroundJobRequestStatus(
        )
        """

    def testBackgroundJobRequestStatus(self):
        """Test BackgroundJobRequestStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
