# coding: utf-8

"""
    TerrAPI

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.i_inventory_catalog import IInventoryCatalog

class TestIInventoryCatalog(unittest.TestCase):
    """IInventoryCatalog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IInventoryCatalog:
        """Test IInventoryCatalog
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IInventoryCatalog`
        """
        model = IInventoryCatalog()
        if include_optional:
            return IInventoryCatalog(
                inventory_type = 'UNKNOWN',
                inventory_point_uri = '',
                initialized = True,
                remote_id = '',
                resource_server = '',
                owner = '',
                type = 'StorageWorkspace',
                status = openapi_client.models.i_resource_status.IResourceStatus(
                    status_code = 'OK', 
                    message = '', ),
                resource_uris = [
                    ''
                    ],
                scopes = [
                    ''
                    ],
                properties = {
                    'key' : [
                        null
                        ]
                    },
                platform_id = '',
                name = '0',
                var_self = '',
                background_job_id = '',
                title = '',
                id = '',
                content_type = openapi_client.models.content_type.ContentType(
                    boundary = '', 
                    char_set = '', 
                    media_type = '', 
                    name = '', 
                    parameters = [
                        null
                        ], ),
                resource_type = 0,
                content_length = 56,
                content_disposition = openapi_client.models.content_disposition.ContentDisposition(
                    disposition_type = '', 
                    parameters = [
                        null
                        ], 
                    file_name = '', 
                    creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    modification_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    inline = True, 
                    read_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    size = 56, ),
                uri = ''
            )
        else:
            return IInventoryCatalog(
                inventory_type = 'UNKNOWN',
                inventory_point_uri = '',
                type = 'StorageWorkspace',
                resource_uris = [
                    ''
                    ],
                properties = {
                    'key' : [
                        null
                        ]
                    },
                name = '0',
        )
        """

    def testIInventoryCatalog(self):
        """Test IInventoryCatalog"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
