# coding: utf-8

# flake8: noqa
"""
    TerrAPI

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.access_token import AccessToken
from openapi_client.models.auth_resource_type import AuthResourceType
from openapi_client.models.background_job_request_status import BackgroundJobRequestStatus
from openapi_client.models.catalog_publication_request import CatalogPublicationRequest
from openapi_client.models.claim_lite import ClaimLite
from openapi_client.models.content_disposition import ContentDisposition
from openapi_client.models.content_type import ContentType
from openapi_client.models.data_casting_enum import DataCastingEnum
from openapi_client.models.data_casting_request import DataCastingRequest
from openapi_client.models.get_job_status401_response import GetJobStatus401Response
from openapi_client.models.http_validation_problem_details import HttpValidationProblemDetails
from openapi_client.models.i_inventory_catalog import IInventoryCatalog
from openapi_client.models.i_inventory_point import IInventoryPoint
from openapi_client.models.i_inventory_sts import IInventorySTS
from openapi_client.models.i_publication_request import IPublicationRequest
from openapi_client.models.i_resource_status import IResourceStatus
from openapi_client.models.i_shared_folder import ISharedFolder
from openapi_client.models.i_storage_point import IStoragePoint
from openapi_client.models.i_storage_sts import IStorageSTS
from openapi_client.models.i_subject import ISubject
from openapi_client.models.i_translator import ITranslator
from openapi_client.models.i_workspace import IWorkspace
from openapi_client.models.import_request import ImportRequest
from openapi_client.models.import_status import ImportStatus
from openapi_client.models.inventory_type import InventoryType
from openapi_client.models.link import Link
from openapi_client.models.principal_context import PrincipalContext
from openapi_client.models.problem_details import ProblemDetails
from openapi_client.models.publication_request import PublicationRequest
from openapi_client.models.publication_status import PublicationStatus
from openapi_client.models.request_status import RequestStatus
from openapi_client.models.request_status_code import RequestStatusCode
from openapi_client.models.resource_deletion_task import ResourceDeletionTask
from openapi_client.models.resource_status_code import ResourceStatusCode
from openapi_client.models.resource_type import ResourceType
from openapi_client.models.share_folder_request import ShareFolderRequest
from openapi_client.models.storage_type import StorageType
from openapi_client.models.sts_inventory import StsInventory
from openapi_client.models.sts_storage import StsStorage
from openapi_client.models.subject import Subject
