# coding: utf-8

"""
    TerrAPI

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AuthResourceType(str, Enum):
    """
    AuthResourceType
    """

    """
    allowed enum values
    """
    URN_COLON_RESOURCE_COLON_STORAGE_COLON_WORKSPACE = 'urn:resource:storage:workspace'
    URN_COLON_RESOURCE_COLON_STORAGE_COLON_SHAREDFOLDER = 'urn:resource:storage:sharedfolder'
    URN_COLON_RESOURCE_COLON_INVENTORY_COLON_CATALOG = 'urn:resource:inventory:catalog'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AuthResourceType from a JSON string"""
        return cls(json.loads(json_str))


