# coding: utf-8

"""
    TerrAPI

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class InventoryType(str, Enum):
    """
    InventoryType
    """

    """
    allowed enum values
    """
    UNKNOWN = 'UNKNOWN'
    GEOSQUARE = 'Geosquare'
    STACAPI = 'StacApi'
    STAC = 'Stac'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InventoryType from a JSON string"""
        return cls(json.loads(json_str))


