# coding: utf-8

"""
    TerrAPI

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ResourceStatusCode(str, Enum):
    """
    ResourceStatusCode
    """

    """
    allowed enum values
    """
    OK = 'OK'
    ERROR = 'ERROR'
    NOT_FOUND = 'NOT_FOUND'
    FORBIDDEN = 'FORBIDDEN'
    UNAUTHORIZED = 'UNAUTHORIZED'
    BAD_REQUEST = 'BAD_REQUEST'
    CONFLICT = 'CONFLICT'
    NOT_IMPLEMENTED = 'NOT_IMPLEMENTED'
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'
    GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT'
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
    UNCLAIMED = 'UNCLAIMED'
    UNKNOWN = 'UNKNOWN'
    PENDING = 'PENDING'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ResourceStatusCode from a JSON string"""
        return cls(json.loads(json_str))


