# coding: utf-8

"""
    TerrAPI

    Terradue Core API v2

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class StorageType(str, Enum):
    """
    StorageType
    """

    """
    allowed enum values
    """
    UNKNOWN = 'unknown'
    S3 = 's3'
    FTP = 'ftp'
    LOCAL = 'local'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StorageType from a JSON string"""
        return cls(json.loads(json_str))


